export const mockStaff = [
  {
    id: 1,
    firstName: "Jane",
    lastName: "Doe",
    title: "Mathematics Teacher",
    department: "Mathematics",
    profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
    bio: "Passionate about making math fun and accessible for all students.",
    expertise: ["Algebra", "Calculus", "Statistics", "Math Club"],
    email: "jane.doe@eduverse.com",
    phone: "555-123-4567",
    officeLocation: "Room 101",
    officeHours: { Monday: "10am-12pm", Wednesday: "2pm-4pm" },
    experience: "12 years",
  },
  {
    id: 2,
    firstName: "John",
    lastName: "Smith",
    title: "Science Department Head",
    department: "Science",
    profileImage: "https://randomuser.me/api/portraits/men/2.jpg",
    bio: "Leading the science department and inspiring curiosity in biology and chemistry.",
    expertise: ["Biology", "Chemistry", "Lab Safety"],
    email: "john.smith@eduverse.com",
    phone: "555-987-6543",
    officeLocation: "Room 202",
    officeHours: { Tuesday: "1pm-3pm", Thursday: "10am-12pm" },
    experience: "15 years",
  },
  {
    id: 3,
    firstName: "Alex",
    lastName: "Nguyen",
    title: "English Literature Instructor",
    department: "English",
    profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "Focused on literature, creative writing, and critical thinking.",
    expertise: ["Literature", "Writing", "Poetry"],
    email: "alex.nguyen@eduverse.com",
    phone: "555-321-6789",
    officeLocation: "Room 303",
    officeHours: { Friday: "9am-11am" },
    experience: "7 years",
  },
  {
    id: 4,
    firstName: "Maria",
    lastName: "Garcia",
    title: "IT Administrator",
    department: "Administration",
    profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "Ensures EduVerse runs smoothly and securely for all students and staff.",
    expertise: ["IT Support", "Networking", "Security"],
    email: "maria.garcia@eduverse.com",
    phone: "555-654-3210",
    officeLocation: "Admin Office",
    officeHours: { Monday: "8am-10am", Thursday: "3pm-5pm" },
    experience: "10 years",
  },
  {
    id: 5,
    firstName: "Priya",
    lastName: "Patel",
    title: "Physics Teacher",
    department: "Science",
    profileImage: "https://randomuser.me/api/portraits/women/5.jpg",
    bio: "Physics is everywhere! I love making the subject relatable and exciting.",
    expertise: ["Physics", "Robotics", "Astronomy"],
    email: "priya.patel@eduverse.com",
    phone: "555-789-1234",
    officeLocation: "Room 204",
    officeHours: { Wednesday: "11am-1pm" },
    experience: "5 years",
  },
  // Add more staff as needed!
];